language: elixir

elixir:
  - '1.8.1'

otp_release:
  - '21.3.7'

services:
  - docker

before_install:
  - sudo service postgresql stop
  - docker-compose build

script:
  - docker-compose run contract-test