version: '3.1'

services:
  bash:
    build: 
      context: .
    command: /bin/bash
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_NAME: go_champs_db
      DATABASE_HOST: db
    volumes:
      - ./:/app

  phoenix:
    build: 
      context: .
    command: bash -c "mix ecto.setup && mix phx.server"
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_NAME: go_champs_db
      DATABASE_HOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: go_champs_db

  unit-test:
    build: 
      context: .
    command: mix test
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_NAME: go_champs_db
      DATABASE_HOST: db
    depends_on:
      - db

  contract-test:
    build: 
      context: ./e2e/
    command: yarn test
    environment:
      API_HOST: http://phoenix:4000/v1
    volumes:
    - ./e2e/specs:/contractTest/specs
    depends_on:
      - phoenix

  vs-code:
    build: 
      context: .
    command: sleep infinity
    volumes:
      - ./:/app